// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:sekaipod/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ExcludeDirectoryModelAdapter());
    registerAdapter(MusicMetadataAdapter());
    registerAdapter(PlaylistModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ExcludeDirectoryModelAdapter());
    registerAdapter(MusicMetadataAdapter());
    registerAdapter(PlaylistModelAdapter());
  }
}
